server:
  port: 18001
eureka:
  instance:
    hostname: "eurekaServer18001"
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      #      defaultZone: "http://localhost:18000:18000/eureka/"
      defaultZone: "http://eurekaServer18000:18000/eureka/"
  server:
    enable-replicated-request-compression: false