server:
  port: 12000

resilience4j:
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 30
        minimum-number-of-calls: 1
        sliding-window-type: TIME_BASED
        sliding-window-size: 10
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 2s
        permitted-number-of-calls-in-half-open-state: 3
        record-exceptions:
          - java.lang.Exception
    instances:
      backendA:
        base-config: default

spring:
  application:
    name: "gateway-server"
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: consumerServer
          uri: lb://consumer-server
          predicates:
            - Path=/cart/getCartById/**
          filters:
            - name: CircuitBreaker
              args:
                name: backendA
                fallbackUri: forward:/fallback
        - id: providerServer
          uri: lb://provider-server
          predicates:
            - Path=/user/getUserById/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "GET, HEAD, POST, PUT, DELETE, OPTIONS"
            allowed-headers: "*"
eureka:
  client:
    service-url:
      defaultZone: "http://eurekaServer18000:18000/eureka/,http://eurekaServer18001:18001/eureka/"
  instance:
    prefer-ip-address: true
    instance-id: "${spring.cloud.client.ip-address}:${server.port}"
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15